manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/zmkfirmware
  - name: englmaxi
    url-base: https://github.com/englmaxi
  - name: damex
    url-base: https://github.com/damex
  projects:
  - name: zmk
    remote: zmkfirmware
    revision: ead91ca094c6cd778574f73b9ae011ddab611c66
    import: app/west.yml  
  - name: zmk-dongle-display
    remote: englmaxi
    revision: main
  - name: zmk-feature-split-esb
    remote: damex
    revision: v0.2.3
    import: true
self:
  path: config
